name: "Test Parall"

on:
  push:
    branches:
      - stupid_idea
env:
    TERM: xterm-256color

jobs:
  core:
    name: "Configure and Deploy Core"
    runs-on: ubuntu-latest
    outputs:
      #matrix: ${{ steps.generate-matrix.outpu      
      core: ${{ steps.generate-matrix.outputs.core }}
      stag: ${{ steps.generate-matrix.outputs.stag }}
      dev: ${{ steps.generate-matrix.outputs.dev }}
    strategy:
      max-parallel: 1
      fail-fast: true
    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Generate Matrix
      id: generate-matrix
      #run: echo "matrix=$(cat matrix.stacks.yaml | yq '.projects' -I0 -o json)" >> $GITHUB_OUTPUT
      run: |
        echo "core=$(cat matrix.stacks.dum.json | yq '.core-services'  -I0 -o json)" >> $GITHUB_OUTPUT
        echo "stag=$(cat matrix.stacks.dum.json | yq '.staging'  -I0 -o json)" >> $GITHUB_OUTPUT
        echo "dev=$(cat matrix.stacks.dum.json | yq '.development'  -I0 -o json)" >> $GITHUB_OUTPUT

  dev:
    name: "Deploy ${{ matrix.projects.name }} development"
    needs: core
    #if: ${{ fromJson(needs.core.outputs.dev.name) != 'dummy' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        projects: ${{ fromJson(needs.core.outputs.dev) }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo ${{ fromJSON(needs.core.outputs.dev.[].name) }}

      - name: Setup Terraform
        uses: ./.github/actions/terraform/init
        with:
          terraform_version: 1.12.2
          stack: ${{ matrix.projects.name }}/${{ matrix.projects.env }}
      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=stacks/${{ matrix.projects.name }}/${{ matrix.projects.env }} plan
        continue-on-error: true
      - name: Terraform Show
        id: show
        run: |
          terraform -chdir=stacks/${{ matrix.projects.name }}/${{ matrix.projects.env }} show tfplan
          rm -f stacks/${{ matrix.projects.name }}/${{ matrix.projects.env }}/tfplan
        continue-on-error: true

  staging:
    name: "Deploy ${{ matrix.projects.name }} staging"
    #if: always()
    needs: [core, dev]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        projects: ${{ fromJson(needs.core.outputs.stag) }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: ./.github/actions/terraform/init
        with:
          terraform_version: 1.12.2
          stack: ${{ matrix.projects.name }}/${{ matrix.projects.env }}
      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=stacks/${{ matrix.projects.name }}/${{ matrix.projects.env }} plan
        continue-on-error: true
