name: "Test Plan"

on:
  push:
    branches:
      - better_matrix
env:
    TERM: xterm-256color

jobs:
  conf:
    name: configuration
    runs-on: ubuntu-latest
    outputs:
      prod: ${{ steps.generate-matrix.outputs.prod }}
      stag: ${{ steps.generate-matrix.outputs.stag }}
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Generate Matrix
      id: generate-matrix
      run: |
        echo "prod=$(cat matrix.stacks.json | yq '.production' -I0 -o json)" >> $GITHUB_OUTPUT
        echo "stag=$(cat matrix.stacks.json | yq '.staging' -I0 -o json)" >> $GITHUB_OUTPUT
        echo "matrix=$(cat matrix.stacks.json | yq  -I0 -o json)" >> $GITHUB_OUTPUT

  stag:
    name: staging
    needs: [conf]
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        stacks: ${{ fromJson(needs.conf.outputs.stag) }}
    uses: ./.github/workflows/reusable_plan.yaml
    env:
      toto: tata
    with:
      stack: ${{ matrix.stacks.name }}
      env: ${{ matrix.stacks.env }}
    secrets:
      anime: ${{ secrets.ANIME }}
  
  prod:
    name: production
    needs: [conf, stag]
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        stacks: ${{ fromJson(needs.conf.outputs.prod) }}
    uses: ./.github/workflows/reusable_plan.yaml
    with:
      stack: ${{ matrix.stacks.name }}
      env: ${{ matrix.stacks.env }}
    secrets:
      anime: ${{ secrets.ANIME }}
