name: "Test Plan"

on:
  push:
    branches:
      - better_matrix
env:
    TERM: xterm-256color

jobs:
  conf:
    name: configuration
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Generate Matrix
      id: generate-matrix
      run: echo "matrix=$(cat matrix.stacks.json | yq  -I0 -o json)" >> $GITHUB_OUTPUT

  dev:
    name: TF
    needs: conf
    if: ${{ matrix.stacks.env == 'development' }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        stacks: ${{ fromJson(needs.conf.outputs.matrix) }}
    uses: ./.github/workflows/reusable_plan.yaml
    with:
      stack: ${{ matrix.stacks.name }}
      env: ${{ matrix.stacks.env }}
