name: "Test Parall"

on:
  push:
    branches:
      - paral
env:
    TERM: xterm-256color

strategy:
  matrix:
    projects: ["hayley", "jenna", "victoria"]

jobs:
  # configure:
  #   runs-ons: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #   - name: Checkout to repository
  #      uses: actions/checkout@v4
  #    - name: Set matrix data
  #      id: set-matrix
  #      run: echo "matrix=$(jq -c . < ./config.json)" >> $GITHUB_OUTPUT
  core:
    name: "Deploy Core"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
    steps:
      - name: "Deploy Core"
        run: echo "deploying Core"

  dev:
    name: "Deploy ${{ matrix.projects }}"
    needs: [core]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: true
    steps:
      - name: Setup Terraform
        uses: ./.github/actions/terraform/init
        with:
          terraform_version: 1.10.5
          stack: ${{ matrix.projects }}/development

  staging:
    name: "Deploy ${{ matrix.projects }}"
    if: alwaus()
    needs: [core, dev]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: true
    steps:
      - name: Setup Terraform
        uses: ./.github/actions/terraform/init
        with:
          terraform_version: 1.10.5
          stack: ${{ matrix.projects }}/staging
